apiVersion: v1
kind: ConfigMap
metadata:
  name: hwpc-config
data:
  config_file.json: |+
    {
      "name": "sensor",
      "verbose": true,
      "frequency": 500,
      "output": {
        "type": "mongodb",
        "uri": "mongodb://root:admin@smartwatts-mongodb.default:27017",
        "database": "db_sensor",
        "collection": "report_0"
      },
      "system": {
        "rapl": {
          "events": ["RAPL_ENERGY_PKG"],
          "monitoring_type": "MONITOR_ONE_CPU_PER_SOCKET"
        },
        "msr": {
          "events": ["TSC", "APERF", "MPERF"]
        }
      },
      "container": {
        "core": {
          "events": [
            "CPU_CLK_THREAD_UNHALTED:REF_P",
            "CPU_CLK_THREAD_UNHALTED:THREAD_P",
            "LLC_MISSES",
            "INSTRUCTIONS_RETIRED"
          ]
        }
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hwpc-sensor-exporter
  labels:
    app.kubernetes.io/name: hwpc-sensor-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hwpc-sensor-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hwpc-sensor-exporter
    spec:
      # hostNetwork: true
      containers:
      - name: hwpc-sensor-exporter
        image: powerapi/hwpc-sensor
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command:
        - /usr/bin/hwpc-sensor 
        - --config-file 
        - /config_file/config_file.json
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /sys
          name: tracing
        - name: config-volume
          mountPath: /config_file
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: tracing
        hostPath:
          path: /sys
          type: Directory
      - name: config-volume
        configMap:
          name: hwpc-config

