apiVersion: v1
kind: ConfigMap
metadata:
  name: smartwatts-config
data:
  config_file.json: |+
    {
      "verbose": true,
      "stream": true,
      "input": {
        "puller": {
          "model": "HWPCReport",
          "type": "mongodb",
          "uri": "mongodb://root:admin@smartwatts-mongodb.default",
          "db": "db_sensor",
          "port": 27017,
          "collection": "report_0"
        }
      },
      "output": {
        "pusher_power": {
          "type": "mongodb",
          "model": "PowerReport",
          "uri": "mongodb://root:admin@smartwatts-mongodb.default",
          "port": 27017,
          "db": "db_out",
          "collection": "prep"
        }
      },
      "cpu-frequency-base": 2300,
      "cpu-frequency-min": 1200,
      "cpu-frequency-max": 3600,
      "cpu-error-threshold": 2.0,
      "disable-dram-formula": true,
      "sensor-report-sampling-interval": 1000
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartwatts-exporter
  labels:
    app.kubernetes.io/name: smartwatts-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smartwatts-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smartwatts-exporter
    spec:
      # hostNetwork: true
      containers:
      - name: smartwatts-exporter
        image: powerapi/smartwatts-formula
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command:
        - python3
        - -m
        - smartwatts
        - --config-file 
        - /config_file/config_file.json
        volumeMounts:
        - name: config-volume
          mountPath: /config_file
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: config-volume
        configMap:
          name: smartwatts-config

